### ISSUE TITLE
Update pyproject.toml to require matplotlib-scalebar > 0.7.0

### ISSUE THREAD

**Issue by rajgiriUW** [SarthakJariwala/seaborn-image#155]
The Matplotlib rcParams Dict doesn't get updated to include scalebar.width_fraction until Release v.0.7.0 of matplotlib-scalebar.

i.e. version check in ```./pyproject.toml``` should probably change from:
 ```matplotlib-scalebar = ">=0.6.2,<0.8.0"```
to
```matplotlib-scalebar = ">=0.7.0,<0.8.0"```

**Comment by SarthakJariwala** [comment]
Thanks @rajgiriUW 

Just released a new version 0.4.3 that requires at least 0.7.0 of `matplotlib-scalebar`
