### ISSUE TITLE
Blend two image into 1 image

### ISSUE THREAD

**Issue by DangLienMinh** [SarthakJariwala/seaborn-image#260]
Hi,

I want to blend two images into one image like in matplotlib. Is it possible? Because when I tried this code, it plotted two images 

`isns.set_image(cmap="magma", origin="upper",despine=True)

        isns.imgplot(im.resize((w, h), Image.ANTIALIAS),alpha=0.5)

        isns.imgplot(dec_attn_weights[0, idx].view(h, w))

        plt.show()`

<img width="944" alt="Capture" src="https://user-images.githubusercontent.com/2697347/131503918-aa7602ad-de9b-45e9-b1e7-5f8668b52e35.PNG">

**Comment by SarthakJariwala** [comment]
Hi @DangLienMinh - Yes, that is possible with the `ax` parameter.

You can do the following - 
```python
ax1 = isns.imgplot(IMG_1)  # Generates first image
ax = isns.imgplot(IMG_2, ax=ax1)  # Adds second image to the axes of the first image
```

Note the `ax=ax1` in the second function.

**Comment by DangLienMinh** [comment]
Hi @SarthakJariwala, Thank you very much for your help.

**Comment by SarthakJariwala** [comment]
You would want to have the `alpha` parameter for the _**second**_ image (the image that you are plotting as the overlay). Otherwise, if the second image is opaque, it will completely block the first image (basically the result that you got).

So, you can try - 
```python
ax = isns.imgplot(dec_attn_weights[0, idx].view(h, w))
ax = isns.imgplot(im.resize((w, h), Image.ANTIALIAS), alpha=0.3, ax=ax)
```

**Comment by DangLienMinh** [comment]
Thank you very much. It worked perfectly
