### ISSUE TITLE
scikit-image requirements on conda-forge

### ISSUE THREAD

**Issue by ChemicalSailor** [SarthakJariwala/seaborn-image#282]
Import error for seaborn-image because difference_of_gaussians not available in the version of scikit-image I have installed. The requirement is for scikit-image >= 0.17. Can this be added to the dependencies on conda-forge so that conda updates dependencies when required.

**Comment by SarthakJariwala** [comment]
Thanks for the report! The constraint was added and [new build uploaded](https://anaconda.org/conda-forge/seaborn-image/files)
