### ISSUE TITLE
Remove "Here"

### ISSUE THREAD

**Issue by brandonStell** [SarthakJariwala/seaborn-image#318]
Opening an issue is probably easier for both of us than a PR but I can submit one if you prefer:

It would be helpful to comment his out:
https://github.com/SarthakJariwala/seaborn-image/blob/161d72b37a37f7ef680645df4b615eea7c2d9a6b/src/seaborn_image/_core.py#L187

**Comment by SarthakJariwala** [comment]
Good catch! 😅 Should be removed in the latest master.
