### ISSUE TITLE
Using map_func on ImageGrid with a list of images modifies the original list

### ISSUE THREAD

**Issue by eugenioLR** [SarthakJariwala/seaborn-image#583]
If you provide a list of images to ImageGrid and function in the map_func attribute the function is applied to the original images and they are permanently changed.

Here is some example code to recreate the issue, first we create 2 random images and we visualize them
```python
img1 = np.random.random((32,32))
img2 = np.random.random((32,32))

image_list = [img1, img2]
isns.ImageGrid(image_list)
```
![output](https://user-images.githubusercontent.com/46348947/229555305-dc4502b8-7af5-47c3-b8fa-390249542ced.png)

Then we use ImageGrid with a function that sets some of the values to 0, notice that the original array is never modified since it is copied before the prodecure

```python
def apply_to_imgs(img):
    replacement = img.copy()
    replacement[5:, :-5] = 0
    return replacement

isns.ImageGrid(image_list, map_func = apply_to_imgs)
```
![output2](https://user-images.githubusercontent.com/46348947/229555774-5f3c154c-46d3-4709-bb96-203aae8914ad.png)

This is all expected behaviour.

Now if we show the original list again without applying the function, the original images have been modified
```python
isns.ImageGrid(image_list)
```
![output3](https://user-images.githubusercontent.com/46348947/229556275-9b8dcec2-a0fd-469d-ac51-a2807eeb7255.png)

This is most likely a bug caused by modifying directly the list passed as an input.

**Comment by SarthakJariwala** [comment]
Good catch! Yeah, certainly a bug. 

We could create a copy before transforming the list with map_func. That should do it. 

I can fix it later today.
