### ISSUE TITLE
Newer versions of python are (probably) not supported.

### ISSUE THREAD

**Issue by eugenioLR** [SarthakJariwala/seaborn-image#660]
I wanted to use this library with some modern code using python 3.11 but i can't get it to work.

When installing via pip in a PC with ArchLinux with python 3.11.5 installed it gives a strange error like the one bellow.  
![image](https://github.com/SarthakJariwala/seaborn-image/assets/46348947/d271c103-d8bb-4f54-8760-be05055882df)

I assume this is an issue with this package, but i don't really know.

**Comment by eugenioLR** [comment]
I can also confirm now that I can still install it with python 3.10.13 without any kind of issues whatsoever.

**Comment by SarthakJariwala** [comment]
Thanks for flagging. I was also able to reproduce install issues on 3.11.5. Looking at the stacktrace, it is likely an issue of capping scikit-image version to <0.18.0

**Comment by SarthakJariwala** [comment]
Just released `0.7.1`, and it resolved install issues for me on Python 3.11.

Can you try it with the new version - `python -m pip install -U seaborn-image` (make sure you use the `-U` flag; otherwise it might try to use the cache)

**Comment by eugenioLR** [comment]
Ok, it works now. Thank you.
