### ISSUE TITLE
New feature for symmetic colormaps on images with negative values

### ISSUE THREAD

**Issue by eugenioLR** [SarthakJariwala/seaborn-image#697]
I have been using this library a lot and one small inconvenience i find all the time is when i want to visualize images with positive and negative values, where i use a color map like "seismic" expecting to find positive values in red and negative values in blue, but the range of values detected don't align.

To put a practical example, here i'm trying to visualize a covariance matrix. 

Using the imgplot indicating only the color map i get the following image:
```isns.imgplot(cov, cmap="seismic")```
![image](https://github.com/SarthakJariwala/seaborn-image/assets/46348947/fc8cd197-7f67-4aaf-9a51-e6a6682d82f2)

To fix this, i have to specify the range of values i want to show
```
vmin = -np.abs(cov).max()
vmax = np.abs(cov).max()
isns.imgplot(cov, cmap="seismic", vmin=vmin, vmax=vmax)
```
![image](https://github.com/SarthakJariwala/seaborn-image/assets/46348947/4b383629-8763-4be6-b62d-940e62f977b5)

It's not that much of an issue, but it gets a bit more cumbersome when I'm showing a grid of images.

It could be a good idea to add a flag to imgplot and other functions to handle this type of images.

**Comment by eugenioLR** [comment]
I forgot to add that if this seems useful i can implement it myself.

**Comment by SarthakJariwala** [comment]
Yeah, I agree with what your suggesting - It would be useful to support it without explicitly setting `vmin` and `vmax`.

Something similar to `robust=True` flag. Maybe `diverging=True`...? Other name suggestions?

PRs are definitely welcome! Feel free to take a crack at it.
